### ISSUE TITLE
Controlling the autocompletion tooltip position

### ISSUE THREAD

**Issue by mgoldenbe** [uiwjs/react-codemirror#524]
The tooltip appears very far to the right from the current position of the cursor: 

![image](https://github.com/uiwjs/react-codemirror/assets/24386790/308b07d4-5754-41ef-b6e9-db6785de7e81)

The surrounding element does not have any transformations.
I would like to have the tooltip appear immediately to the right and below the cursor. Since it looks like the `left` attribute is computed dynamically, here is what I am trying to affect it:

```css
.cm-tooltip-autocomplete.cm-tooltip.cm-tooltip-below {
    transform: translateX(-12em);
}
```

I tried using `px` and `rem`, but cannot figure out the right formula.

So, how can I achieve that the autocompletion tooltip should appear immediately to the right and below the cursor?
