### ISSUE TITLE
How to use/add simplescrollbars?

### ISSUE THREAD

**Issue by prodiphost** [uiwjs/react-codemirror#535]
I want to use simplescrollbars addon with react-codemirror. It save scrollbar space.

Like this https://codemirror.net/5/demo/simplescrollbars.html.

Thank you.

**Comment by jaywcjlove** [comment]
@prodiphost https://codesandbox.io/embed/react-codemirror-example-codemirror-6-https-github-com-uiwjs-react-codemirror-issues-535-l5c9w7?fontsize=14&hidenavigation=1&theme=dark

```css
.cm-scroller::-webkit-scrollbar {
  width: 10px;
}

.cm-scroller::-webkit-scrollbar-track {
  background: red;
}

.cm-scroller::-webkit-scrollbar-thumb {
  background: yellow;
}

.cm-scroller::-webkit-scrollbar-thumb:hover {
  background: blue;
}
```

Or

```jsx
import { EditorView } from "@codemirror/view";
const scrollbarThemeOption = EditorView.theme({
  "& .cm-scroller::-webkit-scrollbar": {
    width: "10px !important"
  },
  "& .cm-scroller::-webkit-scrollbar-track": {
    background: "#333"
  },
  "& .cm-scroller::-webkit-scrollbar-thumb": {
    background: "yellow"
  },
  "& .cm-scroller::-webkit-scrollbar-thumb:hover": {
    background: "blue"
  }
});


<CodeMirror
  value={code}
  height="200px"
  extensions={[scrollbarThemeOption]}
/>
```
