### ISSUE TITLE
How to change the font 

### ISSUE THREAD

**Issue by acsses** [uiwjs/react-codemirror#636]
How to change font included in google fonts?

**Comment by jaywcjlove** [comment]
@acsses like this?

```css
.cm-editor {
  font-family: 'Your Desired Font', sans-serif !important; 
}
```
