### ISSUE TITLE
Is there a way to customize the slider?

### ISSUE THREAD

**Issue by Jesse1786** [uiwjs/react-codemirror#695]
I'm using the VSCode theme for CodeMirror, however my sliders look out of place with the rest of the style:
![image](https://github.com/user-attachments/assets/7d2b8f02-090e-458e-b90f-f858b3f8b62a)

In the VSCode theme preview, their sliders looked much nicer:
![image](https://github.com/user-attachments/assets/47c6aec0-2735-4bf8-a91e-2e497c74e07a)

How would I make my sliders like the ones in the preview?

**Comment by jaywcjlove** [comment]
<img width="938" alt="image" src="https://github.com/user-attachments/assets/097cfb0d-4996-42d8-9416-a36b7fc426b1">

Customizing scrollbar styles using CSS:

### 1. Basic Styles
```css
/* For Webkit browsers (Chrome, Safari) */
::-webkit-scrollbar {
    width: 12px; /* Width of the scrollbar */
    height: 12px; /* Height of the horizontal scrollbar */
}

::-webkit-scrollbar-thumb {
    background-color: #888; /* Color of the scrollbar thumb */
    border-radius: 10px; /* Rounded corners */
}

::-webkit-scrollbar-track {
    background: #f1f1f1; /* Color of the scrollbar track */
}
```

### 2. Change Scrollbar Color on Hover
```css
::-webkit-scrollbar-thumb:hover {
    background-color: #555; /* Thumb color when hovered */
}
```

### 3. Customize Scrollbar Transparency
```css
/* Custom scrollbar transparency */
::-webkit-scrollbar-thumb {
    background-color: rgba(0, 0, 0, 0.5);
}

::-webkit-scrollbar-thumb:hover {
    background-color: rgba(0, 0, 0, 0.8);
}
```

### 4. Add Border to the Scrollbar
```css
::-webkit-scrollbar-thumb {
    background-color: #888;
    border: 3px solid #f1f1f1; /* Border color of the thumb */
    border-radius: 10px;
}
```

### 5. Control Scrollbar Width
```css
/* Narrow scrollbar */
::-webkit-scrollbar {
    width: 8px;
}

::-webkit-scrollbar-thumb {
    background-color: #888;
    border-radius: 4px;
}

/* Wide scrollbar */
::-webkit-scrollbar {
    width: 16px;
}

::-webkit-scrollbar-thumb {
    background-color: #555;
    border-radius: 8px;
}
```

### 6. Apply Styles to Specific Container Only
If you want to apply the scrollbar styles only to a specific container:
```css
.cm-scroller::-webkit-scrollbar {
    width: 10px;
}

.cm-scroller::-webkit-scrollbar-thumb {
    background-color: #00aaff;
    border-radius: 5px;
}
```

### 7. Custom Scrollbar for Firefox
For Firefox, use `scrollbar-width` and `scrollbar-color` to control scrollbar styles:
```css
/* Set scrollbar width */
.cm-scroller {
    scrollbar-width: thin; /* Options: 'auto', 'thin', or 'none' */
    scrollbar-color: #888 #f1f1f1; /* Thumb color and track color */
}
```

### 8. Dark Mode Scrollbar Customization
You can use media queries to change the scrollbar style based on dark mode or light mode:
```css
@media (prefers-color-scheme: dark) {
    ::-webkit-scrollbar-thumb {
        background-color: #444;
    }
    ::-webkit-scrollbar-track {
        background-color: #222;
    }
}
```
